### PR TITLE
add py.typed file

### LINKED ISSUE #176: Add py.typed file to s3path for mypy support
We are missing  py.typed file, see https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages and https://peps.python.org/pep-0561/

mypy will ignore all typing information when that file is missing

I'm currently unavailable to work on this task.
If someone wants to contribute this is a nice one.

### PR DESCRIPTION
**Pull request by mgab**
Add `py.typed` file so that mypy can access the type hints. See https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages and https://peps.python.org/pep-0561/

closes #176

### CODE REVIEW

**Comment by liormizr** [comment]
Hi @mgab 
Thank you for taking this task :-)
2 questions, do we need to add `global-include *.typed` to the MANIFEST.in file?
second question, I see that the py.typed is empty, are you planning to fill it?

I'm planning to deploy a big version in few days
waiting for your feedback to see if we will include this task

**Comment by mgab** [comment]
> do we need to add global-include *.typed to the MANIFEST.in file?

I think it's equivalent to adding it to the `package_data` parameter in `setup.py`, but for consistency probably it's better to add it in the `MANIFEST.in` file instead.

> I see that the py.typed is empty, are you planning to fill it?

AFAIU it's supposed to be [a marker file that just needs to exist](https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-type-information) without any expected content. The docs only [mention](https://typing.readthedocs.io/en/latest/spec/distributing.html#partial-stub-packages) filling it with `partial\n` if the package provides both inline type hints and stubs.

In any case I'll add a comment just as [they do in the mypy package](https://github.com/python/mypy/blob/master/mypy/py.typed) to make clear why it exists

**Review by liormizr — APPROVED** [review]

**Comment by liormizr** [comment]
Hi @mgab

Thank you verry much
I approved the PR and it will be part of version 0.6

**Comment by mgab** [comment]
Oh, I was just making the changes mentioned (use manifest instead of package_Data, and add a comment in py.typed). Are you interested in them?

**Pull request merged**
